apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
stringData:
  username: "" # Replace with your GitHub username
  repo-name: "" # Replace with your repository name
  full-repo-name: "" # Replace with owner/repo format
  token: "" # Replace with your GitHub token
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: Opaque
stringData:
  username: "" # Replace with your Docker/GitHub username
  image-name: "" # Replace with your image name
  token: "" # Replace with your GitHub token
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: version-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
